FROM alpine:3.11
RUN apk add --update --no-cache ruby-full ruby-dev alpine-sdk \
    && gem install bundler:1.17.2 \
    && rm -rf /var/cache/apk/*

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
