version: '3.3'
services:
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net
  
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongodb-exporter:
    image: bitnami/mongodb-exporter:0.11.0
    environment:
      - MONGODB_URI='mongodb://post_db:27017'
    networks:
      - back_net

  blackbox-exporter:
    image: ${USER_NAME}/blackbox
    ports:
      - '9115:9115'
#    command: '--config.file=/config/blackbox.yml'
    networks:
      - back_net
      - front_net

# --------------------------------------------cadvisor

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - back_net

#---------------------------------------------grafana

  grafana:
    image: ${USER_NAME}/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - trickster
    ports:
      - 3000:3000
    networks:
      - back_net
  
#---------------------------------------------alertmanager

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - back_net

#---------------------------------------------influxDB

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb 
    networks:
      - back_net

#---------------------------------------------telegraf

  telegraf:
    image: ${USER_NAME}/telegraf
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 9273:9273
    networks:
      - back_net
  #  depends_on:
  #    - influxdb

  #---------------------------------------------trickster

  trickster:
    image: ${USER_NAME}/trickster
    depends_on:
      - prometheus
    ports:
      - 8480:8480
    networks:
      - back_net


# --------------------------------------------volumes
volumes:
  prometheus_data:
  grafana_data:
  influxdb_data:

# --------------------------------------------networks
networks:
  back_net:
  front_net:
