version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      docker_back_net:
        aliases:
          - comment_db
          - post_db

  ui:
#    build: ./ui
    image: ${USER_NAME}/ui:${UIVER}
    ports:
      - ${PORTAPP}:9292/tcp
    networks:
      - docker_front_net

  post:
#    build: ./post-py
    image: ${USER_NAME}/post:${POSTVER}
    networks:
      - docker_back_net
      - docker_front_net

  comment:
#    build: ./comment
    image: ${USER_NAME}/comment:${COMMENTVER}
    networks:
      - docker_back_net
      - docker_front_net

volumes:
  post_db:

networks:
  docker_back_net:
    external: true
  docker_front_net:
    external: true
  
