---
- name: Packer Docker Install
  become: true
  hosts: all
  tasks:
  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    with_items:
      - "python-apt"
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "gnupg-agent"
      - "software-properties-common"

  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add stable repository Docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    with_items:
      - "python-docker"
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"

  - name: Restart docker
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker
      enabled: yes
